version: '2.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - weather-app
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - weather-app
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "report-events:1:1"

  database:
    image: postgres:latest
    networks:
      - weather-app
    container_name: "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather-app -P weather-app"]
      interval: 3s
      timeout: 2s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=weather-app
      - POSTGRES_USER=weather-app
    ports:
      - "5432:5432"

networks:
  weather-app:
